# Generated by Django 4.2.16 on 2024-10-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.CharField(max_length=10000, verbose_name='本文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
